
services:
  save_pg :
    image : postgres:alpine
    container_name: save_bot_pg
    restart: always
    environment:
      POSTGRES_PASSWORD : 1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  save_bot:
    build: .
    image: save_bot
    container_name: save_bot_con
    restart: always
    depends_on:
      - save_pg
    command:
      sh -c 'python3 main.py'




volumes:
  pgdata: